### ISSUE TITLE
Check what to do with missing HTML metadatas (itemprop, meta, ...)

### ISSUE THREAD

**Issue by benoit74** [openzim/ifixit#18]
Compared to the online website, multiple metadatas have been omitted from the generated files for brevity / simplicity.

We have to confirm whether this is a problem or not, and take the appropriate actions.

**Comment by kelson42** [comment]
From my POV, really important are:
* title
* Charset of the page

We can live without the rest pretty well IMO if they are harder to get.

**Comment by benoit74** [comment]
OK, I suggest that we live with the current situation, I will close the issue, title and charset are already present, we might reopen it later if needed
