### ISSUE TITLE
Missing "illustration" ZIM metadata

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#23]
The kind of "favicon" of te ZIM file itself, see https://wiki.openzim.org/wiki/Metadata

**Comment by benoit74** [comment]
Already fixed in https://github.com/openzim/ifixit/commit/aa8b29756b8d09ef41638fdafc3c77ff8d6726ff
If we are speaking about the same stuff.

**Comment by kelson42** [comment]
Good. Only checked with the latest full ZIM.
