### ISSUE TITLE
Scraper should report about progression

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#43]

**Comment by kelson42** [comment]
@rgaudin Where is the doc for the API?

**Comment by rgaudin** [comment]
There's None 😬

You should should write a JSON file (at the path specified by your option) with the following content:

```json
{
  "done": 3,
  "total": 1870
}
```

We also have an optionnal property for zimit in-which the scraper has a *limit* after which it stops crawling. I don't think that applies for iFixIt but it's like:

```json
{
  "done": 3,
  "total": 1870,
  "limit": {
    "max": 100,
    "hit": false
  }
}
```

Code that reads it is at https://github.com/openzim/zimfarm/blob/master/workers/app/task/worker.py#L159

**Comment by benoit74** [comment]
@rgaudin do you confirm it is ok if the total is increasing during the scraping? Typical the scraper will discover new items to scrape while scraping other items, so while I could make a first guess on the total number of items to scrape, the total will keep increasing while progressing.
