### ISSUE TITLE
Do not scrape items twice because their key is once an int and once a str

### ISSUE THREAD

**Issue by benoit74** [openzim/ifixit#49]
There is many title conflicts (1442 in the first run of scrapper v0.1.0) displayed in the log:

E.g.
```
[MainThread::2022-04-19 16:44:48,448] DEBUG:Processing guide 112509
Impossible to add C/guides/guide_112509.html
  dirent's title to add is : Battery disassembly
  existing dirent's title is : Battery disassembly
```

This is however not raising a real error + it seems the entry is however present in the final ZIM.

```
> zimdump list --details --url guides/guide_112509.html ifixit_fr_all_2022-04.zim
path: guides/guide_112509.html
	title:           Battery disassembly
	idx:             24466
	type:            item
	mime-type:       text/html
	item size:    22997
```

**Comment by benoit74** [comment]
@rgaudin @kelson42 Is it a know issue? Should I care about it or is it just a "false error"?

**Comment by kelson42** [comment]
@benoit74 Yes, this is possible to have many article with the same title (but not the same URL obviously). But this can lead to confusion as you will have (for example in the suggestions) different content "behind" the same "label".

**Comment by rgaudin** [comment]
@benoit74 the *dirent title* has nothing to do with the Entry Title that you would consider the *page title*. Here, it means the URL (path) of your article in the ZIM.
URLs in the ZIM must be unique so if you try to add twice using the same URL, you'll get this message. Only the first addition is stored in the ZIM.

**Comment by benoit74** [comment]
Oh no, this is indeed a bug.
We scraped this guide 112509 twice.

**Comment by benoit74** [comment]
OK, this is due to the fact that I'm building a set of items already scraped, but "112509" (string) is different than 112509 (int) and sometimes the scrapper get the item ID as a string (because as part of an URL) and other times as an int (because attribute of a JSON object). This creates duplicates.

**Comment by kelson42** [comment]
Looks like you have a found an easy way to speed-up the scrape ;)

**Comment by benoit74** [comment]
This is unfortunately only for 1442 items that we scrape twice (out of 44341 guides + categories + ...) ^^
