### ISSUE TITLE
Some missing guides are not added because of missing title which is indeed known

### ISSUE THREAD

**Issue by benoit74** [openzim/ifixit#75]
Scenario:
- a category has a link to a guide, so we normalize its href
```
[MainThread::2022-05-07 21:47:12,831] DEBUG:Normalizing href https://fr.ifixit.com/Guide/-/149003
[MainThread::2022-05-07 21:47:13,448] DEBUG:Result is /Tutoriel/JBL+Partybox+battery+Replacement/149003
```
- the guide is finally not accessible, so we want to add a redirect but we consider we do not yet know its title:
```
[MainThread::2022-05-09 12:19:42,945] INFO:  Scraping guide 149003 (479 items remaining)
[MainThread::2022-05-09 12:19:42,945] DEBUG:Retrieving https://fr.ifixit.com/api/2.0/guides/149003?langid=fr
[MainThread::2022-05-09 12:19:43,192] DEBUG:Retrieving https://fr.ifixit.com/api/2.0/guides/149003?langid=en
[MainThread::2022-05-09 12:19:43,459] WARNING:Missing guide 149003
[MainThread::2022-05-09 12:19:43,463] WARNING:Cannot add redirect for guide 149003 in error
```

This scenario happened on 9th of May 2022 but seems to be linked to a change between the 'jbl_partybox' category scraping and the guide 149003 scraping. Looks like the guide has been removed in-between.

Since it will continue to happen, it might be great to retrieve the guide title while normalizing URLs (

**Comment by kelson42** [comment]
These kind of scenarios are mean. If something can be build without complexifying too much the code then it should be done. Otherwise, we use, to just live we this kind of imperfection.

**Comment by benoit74** [comment]
Agreed about the fact this is very mean 🤣
And agreed about the fact that we should not add too much complexity to fix
this, since it is a real edge case.

**Comment by benoit74** [comment]
Won't fix for now, let's see if this happens too much (consequence is limited anyway)
