### ISSUE TITLE
Add plateform limit for ifixit

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#80]
Allowing only one scrape at the same time. There is no complain so far on their side, but would prefer to act earlier than later.

**Comment by benoit74** [comment]
@kelson42 @rgaudin How is it done usually ? Do you have a sample implementation ?

**Comment by rgaudin** [comment]
There's nothing to do on scraper side ; @kelson42 incorrectly created this ticket on this repo. It should be on the zimfarm.

**Comment by benoit74** [comment]
@rgaudin thanks for your confirmation, this is also what I was thinking, I had difficulty to imagine a solution software side for something which could be run anywhere by anyone. I will close this issue then.
