### ISSUE TITLE
Translate labels in all languages

### ISSUE THREAD

**Issue by benoit74** [openzim/ifixit#9]
All labels used in category and guide pages have to be translated in the 12 languages supported by Kiwix.

These translations are stored in constants.py, in two dicts, CATEGORY_LABELS and GUIDE_LABELS.

Missing Translations : de, es, it, tr, jp, nl, ru, zh, ko

You will find screenshots of where you might find these labels in English below (this could however have changed, since underlying data is dynamic by nature).
- https://www.ifixit.com/Device/Mac
- https://www.ifixit.com/Device/Apple_Watch
- https://www.ifixit.com/Device/Logitech__G502_Hero
- https://www.ifixit.com/Guide/MacBook+Air+11-Inch+Late+2010+Battery+Replacement/4384
- https://www.ifixit.com/Teardown/Apple+Watch+Teardown/40655

Beware of maintaining necessary spaces and punctuation in the label. Some small adaptations might be necessary is the templates HTML code for some languages where the order of words is different.

For every language :
- Add the URL here:
https://github.com/openzim/ifixit/blob/a77b75caadf3d3e1350da2a531cd526611474678/ifixit2zim/constants.py#L21-L24
- Add all labels in CATEGORY_LABELS and GUIDE_LABELS below

### CATEGORY_LABELS

author:
![image](https://user-images.githubusercontent.com/7102089/162203882-c31524ba-e371-4308-bad2-01f94fdd15b5.png)

categories:
![image](https://user-images.githubusercontent.com/7102089/162203906-4410d3c7-8800-4153-b1a9-4e7d6abdfc72.png)

featured_guides:
![image](https://user-images.githubusercontent.com/7102089/162203948-a3d96ce6-1d89-42c9-b36f-db0e5a7835d7.png)

technique_guides:
![image](https://user-images.githubusercontent.com/7102089/162203967-ab696bfc-546e-4b0a-bdaf-3a0382ff0783.png)

replacement_guides:
![image](https://user-images.githubusercontent.com/7102089/162204095-a6c13f46-b342-4d43-af58-c93bb732485f.png)

teardown_guides:
![image](https://user-images.githubusercontent.com/7102089/162204140-494bacb3-1243-4058-8bba-5721a2039662.png)

related_pages:
![image](https://user-images.githubusercontent.com/7102089/162204205-f5dd259e-b87b-4927-b844-909e8b946cd9.png)

in_progress_guides:
![image](https://user-images.githubusercontent.com/7102089/162204252-cb60f98a-c6a7-4eee-a804-022746800ccc.png)

disassembly_guides:
![image](https://user-images.githubusercontent.com/7102089/162204350-e06ebfae-ea0a-45f6-b800-e3675c1020be.png)

repairability:
![image](https://user-images.githubusercontent.com/7102089/162204397-f4c1445d-dc16-4437-b34d-d0d16d2f7a0f.png)

### GUIDE_LABELS

written_by, difficulty, steps, time_required, sections, flags:
![image](https://user-images.githubusercontent.com/7102089/162205559-ca4ca676-a5b5-42ab-a306-27a4543acb3e.png)

introduction, step_no:
![image](https://user-images.githubusercontent.com/7102089/162205754-5fa85788-3215-4f4a-a528-a9835ccbfd76.png)

conclusion, author, reputation :
![image](https://user-images.githubusercontent.com/7102089/162206309-909b6e7c-1e97-4d7d-bcab-da6dc5c3906b.png)

published, teardown:
![image](https://user-images.githubusercontent.com/7102089/162206416-69d2fcf1-c826-46ac-a992-fea7a76e8021.png)

member_since:
![image](https://user-images.githubusercontent.com/7102089/162206445-29668e24-a8db-453f-80d6-3bbd07a26f66.png)

**Comment by kelson42** [comment]
We will need to do that with Translatewiki.net

**Comment by benoit74** [comment]
I'm unsure if it's worth setting up a project over there, all labels have
already been translated on iFixit website, so I would say we better have to
just grab them there by hand (my proposal since its a one time effort) or
even automatically.
